### PR TITLE
Pull HOLIDAY_SCHEDULE from PS_EMPLOYEES2

### PR DESCRIPTION
**Pull request by jeff-clay**
[HS Ticket](https://secure.helpscout.net/conversation/2564140970/1134005/)

This will allow us to pull in the holiday schedule for an employee in order to use it in etimesheet.

### CODE REVIEW

**Comment by jeff-clay** [comment]
Do I need to change the version number of this from 9.4 to 9.5?

**Comment by wrandall22** [comment]
You will need to bump the version, yes. Also note that eTimesheet is using version 8, so you may want to check to see that there are no breaking changes between 8 and 9.

**Comment by jeff-clay** [comment]
Thanks for catching that. Etimesheet compiles and passes all tests with 9.4.

**Review by wrandall22 — APPROVED** [review]

**Comment by jeff-clay** [comment]
Interestingly, a test is failing that has nothing to do with my changes. I checked out the code before my changes and it still fails. I've spent an hour or two trying to figure out why it would fail, and I can't find a reason why it would return false. Specifically, [this assertion](https://github.com/CruGlobal/util/blob/9b50f01e8a17f48677746af9de3c02e2d92d602a/src/test/java/org/ccci/util/TimeUtilTest.java#L137) returns false when it seems to be true as I look up historical time boundaries. Am I missing something obvious?

I don't know if other developers who worked on this code experienced the failure, but I don't want to have a failing test perpetually out there.

**Comment by wrandall22** [comment]
Does the error look like this?

```
java.lang.VerifyError: (class: ASMAccessorImpl_16854213981712772812080, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
```

**Comment by jeff-clay** [comment]
I haven't seen that in the error in the terminal, though that's somewhat helpful it that's what you get.

Below is what I get in the surefire report. It just says the assertion fails.

 ```
<testcase name="testIsDaylightSavingsTimeBoundary" time="0.002" classname="org.ccci.util.TimeUtilTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.ccci.util.TimeUtilTest.testIsDaylightSavingsTimeBoundary(TimeUtilTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
```

**Comment by wrandall22** [comment]
Does this error occur on the master branch?

**Comment by jeff-clay** [comment]
Yes, it does. 

When I do `System.out.println(TimeUtil.isDaylightSavingsTimeBoundary(boundary, eastern));`, it actually returns as false, when it should be true.

**Comment by wrandall22** [comment]
I do not get test failures in either branch.

**Comment by hlbraddock** [comment]
@jeff-clay 
I'm not seeing `9.5` installed in https://cruglobal.jfrog.io/ui/repos/tree/General/maven-cru-private-releases-local/org/ccci/util.
Were you waiting on completion of https://github.com/CruGlobal/etimesheet/pull/57 before installing it?

**Comment by jeff-clay** [comment]
I may not have done this correctly, but I installed 9.5-SNAPSHOT here: https://cruglobal.jfrog.io/ui/repos/tree/General/maven-cru-private-snapshots-local/org/ccci/util/9.5-SNAPSHOT/util-9.5-20240411.191218-1.jar?clearFilter=true

I may need to adjust some things.

**Pull request merged**
